version: '3'
services:
 redis_dfspa:
   image: "redis:5.0.4-alpine"
 sim_dfspa:
   image: mojaloop/mojaloop-simulator:latest
   env_file: docker/sim-backend-dfspa.env
   ports:
     - "3400:3000"
     - "3401:3001"
     - "3403:3003"
   depends_on:
     - scheme-adapter_dfspa
 scheme-adapter_dfspa:
   image: "mojaloop/sdk-scheme-adapter:v9.4.5"
   env_file: docker/scheme-adapter-dfspa.env
   ports:
     - "3500:3000"
     - "3501:4000"
   depends_on:
     - redis_dfspa