version: "3.7"

networks:
  ml-mojaloop-net:
    name: ml-mojaloop-net

services:
  
  ##
  # Core Services
  ##
  # als-oracle-pathfinder:
    # image: mojaloop/als-oracle-pathfinder:v8.7.1
    # container_name: als_account-lookup-service

  account-lookup-service:
    image: mojaloop/account-lookup-service:v9.3.0
    container_name: als_account-lookup-service
    user: root
    command:
      - "sh"
      - "-c"
      - "sh /opt/wait-for/wait-for-account-lookup-service.sh && node src/index.js server"
    ports:
      - "4001:4001"
      - "4002:4002"
    networks:
      - ml-mojaloop-net
    depends_on:
      - mysql-als
      - central-ledger
    volumes:
      - ./docker/account-lookup-service/default.json:/opt/account-lookup-service/config/default.json
      - ./docker/wait-for:/opt/wait-for
    environment:
      - "ALS_DISPLAY_ROUTES=false"
      - "LOG_LEVEL=debug"
    healthcheck:
      test: ["CMD", "sh", "-c" ,"apk --no-cache add curl", ";", "curl", "http://localhost:4001/health"]
      timeout: 20s
      retries: 10
      interval: 30s

  ml-api-adapter:
    image: mojaloop/ml-api-adapter:v9.3.0
    container_name: ml_ml-api-adapter
    user: root
    command:
      - "sh"
      - "-c"
      - "sh /opt/wait-for/wait-for-ml-api-adapter.sh && node src/api/index.js"
    ports:
      - "3000:3000"
    environment:
      - LOG_LEVEL=info
      - CSL_LOG_TRANSPORT=file
    volumes:
      # override the default values with our own - this is because the KAFKA_HOST env variable is ignored for some reason
        - ./docker/ml-api-adapter/default.json:/opt/ml-api-adapter/config/default.json
        - ./docker/wait-for:/opt/wait-for
    networks:
      - ml-mojaloop-net
    depends_on:
      - central-ledger
      - kafka
    healthcheck:
      test: ["CMD", "sh", "-c" ,"apk --no-cache add curl", ";", "curl", "http://localhost:3000/health"]
      timeout: 20s
      retries: 10
      interval: 30s

  central-ledger:
    image: mojaloop/central-ledger:v9.3.0-hotfix.1
    container_name: ml_central-ledger
    user: root
    command:
      - "sh"
      - "-c"
      - "sh /opt/wait-for/wait-for-central-ledger.sh && node src/api/index.js"
      # - "sh /opt/wait-for/wait-for-central-ledger.sh && tail -f /dev/null"
    links:
      - mysql-cl
      - kafka
    ports:
      - "3001:3001"
    volumes:
      # override the default values with our own
       - ./docker/central-ledger/default.json:/opt/central-ledger/config/default.json
       - ./docker/wait-for:/opt/wait-for
    depends_on:
      - mysql-cl
      - kafka
    environment:
      - CLEDG_SIDECAR__DISABLED=true
    networks:
      - ml-mojaloop-net
    healthcheck:
      test: ["CMD", "bash", "-c" ,"apk --no-cache add curl", ";", "curl", "http://localhost:3001/health"]
      timeout: 20s
      retries: 10
      interval: 30s

  quoting-service:
    image: mojaloop/quoting-service:v9.3.2-snapshot
    container_name: ml_quoting-service
    user: root
    ports:
      - "3002:3002"
    environment:
      - CSL_LOG_TRANSPORT=file
    volumes:
      - ./docker/quoting-service/default.json:/opt/quoting-service/config/default.json
    depends_on:
      - mysql-cl
      - central-ledger
    environment:
      - CLEDG_SIDECAR__DISABLED=true
    networks:
      - ml-mojaloop-net
    healthcheck:
      test: ["CMD", "bash", "-c" ,"apk --no-cache add curl", ";", "curl", "http://localhost:3002/health"]
      timeout: 20s
      retries: 10
      interval: 30s

  mysql-cl:
    image: mysql/mysql-server
    container_name: mysql_cl
    ports:
      - "3307:3306"
    volumes:
      - ./docker/sql-init/:/docker-entrypoint-initdb.d/
    environment:
      - MYSQL_USER=${DBUSER:-central_ledger}
      - MYSQL_PASSWORD=${DBPASS:-password}
      - MYSQL_DATABASE=${DBUSER:-central_ledger}
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
    networks:
      - ml-mojaloop-net
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "mysql"]
      timeout: 20s
      retries: 10
      start_period: 40s
      interval: 30s
  
  mysql-als:
    image: mysql/mysql-server
    container_name: mysql_als
    ports:
      - "3306:3306"
    volumes:
      - ./docker/sql-init-als/:/docker-entrypoint-initdb.d/
    environment:
      - MYSQL_USER=${DBUSER:-account_lookup}
      - MYSQL_PASSWORD=${DBPASS:-password}
      - MYSQL_DATABASE=${DBUSER:-account_lookup}
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
    networks:
      - ml-mojaloop-net
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "mysql-als"]
      timeout: 20s
      retries: 10
      start_period: 40s
      interval: 30s

  kafka:
    image: johnnypark/kafka-zookeeper:2.3.0
    container_name: ml_kafka
    # Disable logging as it is far too verbose for debugging locally
    logging:
      driver: none
    volumes:
      - ./docker/kafka/:/opt/kafka_2.12-2.3.0/config/
    ports:
      - "2181:2181"
      - "9092:9092"
    environment:
      - ZOO_LOG4J_PROP=WARN
    networks:
      - ml-mojaloop-net
    healthcheck:
      test: ["CMD" ,"/opt/kafka_2.12-2.3.0/bin/kafka-broker-api-versions.sh","--bootstrap-server","localhost:9092"]
      timeout: 20s
      retries: 10
      start_period: 40s
      interval: 30s

  ##
  # DFSP Simulators
  ## 

  # TODO: We are using the legacy simulator here, but we need to update this to use the `mojaloop/mojaloop-simulator` image

  sim_dfspa:
    image: mojaloop/simulator:v9.3.2
    container_name: simulator
    ports:
      - "8444:8444"
    environment:
      - TRANSFERS_ENDPOINT=ml-api-adapter:3000
      - TRANSFERS_FULFIL_RESPONSE_DISABLED=false
      - QUOTES_ENDPOINT=quoting-service:3002
      - PARTIES_ENDPOINT=account-lookup-service:4002
      - TRANSFERS_FULFILMENT=XoSz1cL0tljJSCp_VtIYmPNw-zFUgGfbUqf69AagUzY
      - TRANSFERS_CONDITION=HOr22-H3AfTDHrSkPjJtVPRdKouuMkDXTR4ejlQa8Ks
      - TRANSFERS_ILPPACKET=AQAAAAAAAADIEHByaXZhdGUucGF5ZWVmc3CCAiB7InRyYW5zYWN0aW9uSWQiOiIyZGY3NzRlMi1mMWRiLTRmZjctYTQ5NS0yZGRkMzdhZjdjMmMiLCJxdW90ZUlkIjoiMDNhNjA1NTAtNmYyZi00NTU2LThlMDQtMDcwM2UzOWI4N2ZmIiwicGF5ZWUiOnsicGFydHlJZEluZm8iOnsicGFydHlJZFR5cGUiOiJNU0lTRE4iLCJwYXJ0eUlkZW50aWZpZXIiOiIyNzcxMzgwMzkxMyIsImZzcElkIjoicGF5ZWVmc3AifSwicGVyc29uYWxJbmZvIjp7ImNvbXBsZXhOYW1lIjp7fX19LCJwYXllciI6eyJwYXJ0eUlkSW5mbyI6eyJwYXJ0eUlkVHlwZSI6Ik1TSVNETiIsInBhcnR5SWRlbnRpZmllciI6IjI3NzEzODAzOTExIiwiZnNwSWQiOiJwYXllcmZzcCJ9LCJwZXJzb25hbEluZm8iOnsiY29tcGxleE5hbWUiOnt9fX0sImFtb3VudCI6eyJjdXJyZW5jeSI6IlVTRCIsImFtb3VudCI6IjIwMCJ9LCJ0cmFuc2FjdGlvblR5cGUiOnsic2NlbmFyaW8iOiJERVBPU0lUIiwic3ViU2NlbmFyaW8iOiJERVBPU0lUIiwiaW5pdGlhdG9yIjoiUEFZRVIiLCJpbml0aWF0b3JUeXBlIjoiQ09OU1VNRVIiLCJyZWZ1bmRJbmZvIjp7fX19
      - LOG_LEVEL=debug

    networks:
      - ml-mojaloop-net
    healthcheck:
      test: ["CMD", "sh", "-c" ,"apk --no-cache add curl", ";", "curl", "http://localhost:8444/health"]
      timeout: 20s
      retries: 10
      interval: 30s


  # New simulators and required dependencies.
  # refer to note above
  # 
  # redis_dfspa:
  #   image: "redis:5.0.4-alpine"
  #   networks:
  #     - ml-mojaloop-net

  # sim_dfspa:
  #   image: mojaloop/mojaloop-simulator:latest
  #   env_file: docker/sim-backend-dfspa.env
  #   ports:
  #     - "3400:3000"
  #     - "3401:3001"
  #     - "3403:3003"
  #   networks:
  #     - ml-mojaloop-net
  #   depends_on:
  #     - scheme-adapter_dfspa

  # scheme-adapter_dfspa:
  #   image: "mojaloop/sdk-scheme-adapter:v9.4.5"
  #   env_file: docker/scheme-adapter-dfspa.env
  #   ports:
  #     - "3500:4000"
  #     - "3501:4001"
  #   networks:
  #     - ml-mojaloop-net
  #   depends_on:
  #     - redis_dfspa

  # redis_dfspb:
  #   image: "redis:5.0.4-alpine"
  #   networks:
  #     - ml-mojaloop-net

  # sim_dfspb:
  #   image: mojaloop/mojaloop-simulator:latest
  #   env_file: docker/sim-backend-dfspb.env
  #   ports:
  #     - "3600:3000"
  #     - "3601:3001"
  #     - "3603:3003"
  #   networks:
  #     - ml-mojaloop-net
  #   depends_on:
  #     - scheme-adapter_dfspb

  # scheme-adapter_dfspb:
  #   image: "mojaloop/sdk-scheme-adapter:v9.4.5"
  #   env_file: docker/scheme-adapter-dfspb.env
  #   ports:
  #     - "3700:3000"
  #     - "3701:4000"
  #   networks:
  #     - ml-mojaloop-net
  #   depends_on:
  #     - redis_dfspb

